name: Manual destroy pipeline

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: 'Type "DESTROY" to confirm destruction of resources'
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  destroy-terraform:
    runs-on: ubuntu-latest
    env:
      TF_VAR_ssh_key_name: ${{ vars.SSH_KEY_NAME }}
      TF_VAR_size: ${{ vars.SIZE }}
      TF_VAR_name: ${{ vars.NAME }}
      TF_VAR_apex_domain: ${{ vars.APEX_DOMAIN }}
      TF_VAR_subdomain: ${{ vars.SUBDOMAIN }}
      TF_VAR_admin_ips: ${{ vars.ADMIN_IPS_CSV }}
      DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_API_TOKEN }}
      TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      TF_VAR_pvt_key: ${{ secrets.SSH_PRIV_KEY }}
      TF_TOKEN_app_terraform_io: ${{ secrets.HCP_TERRAFORM_TOKEN }}
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Check Confirmation Input
        run: |
          if [ "${{ github.event.inputs.confirmation }}" != "DESTROY" ]; then
            echo "Invalid confirmation input. Aborting."
            exit  1
          fi
        working-directory: ""

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Destroy
        run: terraform destroy -no-color -input=false -auto-approve